//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BFN.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommiteRecord
    {
        public int Id { get; set; }
        public string CommiteName { get; set; }
        public string CommiteDetails { get; set; }
        public Nullable<double> CommiteAmount { get; set; }
        public Nullable<int> CommiteMonths { get; set; }
        public Nullable<System.DateTime> CommiteStartDate { get; set; }
        public Nullable<System.DateTime> CommiteEndDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public string LastUpdatedBy { get; set; }
    }
}
