//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BFN.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.CompanyUsers = new HashSet<CompanyUser>();
            this.Shops = new HashSet<Shop>();
            this.ShopCompanyHandOvers = new HashSet<ShopCompanyHandOver>();
        }
    
        public int Id { get; set; }
        public string CompanyName { get; set; }
        public long CompanyCVR { get; set; }
        public string CompanyAddress { get; set; }
        public string CompanyBankAccountNo { get; set; }
        public string CompanyEmail { get; set; }
        public Nullable<bool> BankAccountConsent { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<int> Dealer { get; set; }
        public int ParentId { get; set; }
        public bool IsChain { get; set; }
        public bool IsActive { get; set; }
        public string LastUpdatedBy { get; set; }
        public string OwnerName { get; set; }
        public string CompanyAddress2 { get; set; }
        public Nullable<int> CompanyPostCode { get; set; }
        public string CompanyCityName { get; set; }
    
        public virtual Company Company1 { get; set; }
        public virtual Company Company2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyUser> CompanyUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop> Shops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopCompanyHandOver> ShopCompanyHandOvers { get; set; }
    }
}
