//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BFN.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstallmentRec
    {
        public int Id { get; set; }
        public int FK_CommiteId { get; set; }
        public Nullable<System.DateTime> InstallmentMonth { get; set; }
        public Nullable<double> InstallmentAmount { get; set; }
        public Nullable<int> InstallmentNumber { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public string InstallmentDetails { get; set; }
    }
}
