//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BFN.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shop()
        {
            this.ShopContactPersons = new HashSet<ShopContactPerson>();
            this.ShopTimeTemplates = new HashSet<ShopTimeTemplate>();
            this.ShopUsers = new HashSet<ShopUser>();
            this.ShopCompanyHandOvers = new HashSet<ShopCompanyHandOver>();
        }
    
        public int Id { get; set; }
        public string ShopName { get; set; }
        public string ShopAddress { get; set; }
        public string ShopEAN { get; set; }
        public string ShopCARDEX { get; set; }
        public Nullable<int> ShopFrellationsNummerCategoryId { get; set; }
        public string ShopInformation { get; set; }
        public string ShopCodeLockInfo { get; set; }
        public string ShopBFNNumber { get; set; }
        public int CompanyId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public bool IsActive { get; set; }
        public string LastUpdatedBy { get; set; }
        public int PreviousShopId { get; set; }
        public bool IsLocked { get; set; }
        public Nullable<System.DateTime> InagurationDate { get; set; }
        public Nullable<System.DateTime> TerminatinonDate { get; set; }
        public string Gross { get; set; }
        public string OwnerName { get; set; }
        public string OwnerEmail { get; set; }
        public string ShopAddress2 { get; set; }
        public Nullable<int> ShopPostCode { get; set; }
        public string ShopCityName { get; set; }
        public bool DailyNewsPaper { get; set; }
        public bool Magazines { get; set; }
        public bool Publisher { get; set; }
        public bool ForeignNewspapers { get; set; }
        public bool ForeignWeeklyMagazines { get; set; }
        public bool ForeignPublishers { get; set; }
        public Nullable<int> NewsPaperDeliveryOptionId { get; set; }
        public Nullable<int> ccif { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual DeliveryOption DeliveryOption { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopContactPerson> ShopContactPersons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopTimeTemplate> ShopTimeTemplates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopUser> ShopUsers { get; set; }
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopCompanyHandOver> ShopCompanyHandOvers { get; set; }
    }
}
