//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BFN.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopTimeTemplateHistory
    {
        public int Id { get; set; }
        public int ShopTimeTemplateId { get; set; }
        public string TemplateName { get; set; }
        public string TemplateDescription { get; set; }
        public System.DateTime TemplateDateFrom { get; set; }
        public System.DateTime TemplateDateTo { get; set; }
        public int ShopId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public bool IsActive { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<bool> IsHoliday { get; set; }
    }
}
